### ISSUE TITLE
Errors with stage templates

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#1024]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

- [ ] Stage templates are not filtered by kind, and there is an empty row

![image](https://user-images.githubusercontent.com/3390333/58379505-b94beb00-7fd6-11e9-849d-e8eb61a53fd7.png)

- [ ] Some fields are missing when update stage template

![image](https://user-images.githubusercontent.com/3390333/58379548-91a95280-7fd7-11e9-9414-fa7d23c57217.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/assign @huxiangtao

**Comment by cd1989** [comment]
![image](https://user-images.githubusercontent.com/16573984/58412835-de5d5e00-80a9-11e9-9d5c-3511d25ddbda.png)

 Split lines on ';' when display 'cmd'

**Comment by huxiangtao** [comment]
cause there is one more type which named 'code-scan', so Left navigation side nav will display one empty row
