### ISSUE TITLE
Integrations list API return duplicated integrations

### ISSUE THREAD

**Issue by cd1989** [caicloud/cyclone#1029]
**Is this a BUG REPORT or FEATURE REQUEST?**:

`/apis/v1alpha1/integrations`

/kind bug

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by supereagle** [comment]
It is caused by the default value of `includePublic` query param, refer to https://github.com/caicloud/cyclone/blob/master/pkg/server/apis/v1alpha1/descriptors/integration.go#L29-L34
