### ISSUE TITLE
Security Alerts

### ISSUE THREAD

**Issue by zhujian7** [caicloud/cyclone#1123]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

Security Alerts:
- Upgrade **handlebars** to version 4.0.14 or later.
- Upgrade **js-yaml** to version 3.13.1 or later
- Upgrade **marked** to version 0.6.1 or later

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/36154065/59168674-4c555b00-8b69-11e9-920d-7d85c956c7e8.png)
![image](https://user-images.githubusercontent.com/36154065/59168694-668f3900-8b69-11e9-849b-5addf8eead6f.png)
![image](https://user-images.githubusercontent.com/36154065/59168701-77d84580-8b69-11e9-9121-92d043916b41.png)

**Comment by supereagle** [comment]
Have been fixed by #1127

/close
