### ISSUE TITLE
Problem when update workflow stage

### ISSUE THREAD

**Issue by cd1989** [caicloud/cyclone#1131]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

When click a stage to update in workflow, the display form is incorrect

![image](https://user-images.githubusercontent.com/16573984/59249658-dc71ce00-8c57-11e9-84cd-fd672c2e5a35.png)

Close the slide window and click it again, it will become normal.

![image](https://user-images.githubusercontent.com/16573984/59249789-2b1f6800-8c58-11e9-8655-548b18580efc.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by qiuxiaolian** [comment]
fixed in https://github.com/caicloud/cyclone/pull/1309

**Comment by supereagle** [comment]
Have fixed
/close
