### ISSUE TITLE
install fail:metadata is required

### ISSUE THREAD

**Issue by liangyuanpeng** [caicloud/cyclone#1178]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
> /kind bug

**What happened**:

run 
``
helm install -name cyclone --namespace cyclone-system ./helm/cyclone
``
got some err
``
Error: metadata is required
``

**What you expected to happen**:
Successful installation cyclone

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
helm version v3.0.0-alpha.1

**Comment by supereagle** [comment]
Cyclone only officially supports Helm v2.10+, still not supports Helm v3.0.0-alpha.1. 
Please have a try with Helm v2.10+, let me know if there are any problems.

**Comment by liangyuanpeng** [comment]
ok, thank you
