### ISSUE TITLE
Slack invite link is no longer active, is it alive?

### ISSUE THREAD

**Issue by tosone** [caicloud/cyclone#1289]
Slack invite link is no longer active, is it alive?

/kind bug

**Comment by supereagle** [comment]
Yes. Do you use the links mentioned in https://github.com/caicloud/cyclone#community?

**Comment by tosone** [comment]
Yes.

**Comment by supereagle** [comment]
I have tested, these links are correct.

**Comment by tosone** [comment]
[Sign up](https://join.slack.com/t/cycloneworkflow/shared_invite/enQtNjQ2MDI1MTM1NDg4LTI0NzhmOGY1NjU2NDJhZGNmODNmZDQ5MWJmZjdmNzdlOTc2Yjc1N2M0MjZjYWZiODUyMzViMDZhODYzOTI5MDE) is invalid. Response me this:

![](https://tc.tosone.cn/20190929105325.jpg)

**Comment by supereagle** [comment]
Sorry, the sign up link is expired. I have updated it, please try the new link in README.md
