### ISSUE TITLE
sonar scan: stage should be failed when the quality gate not pass

### ISSUE THREAD

**Issue by zhujian7** [caicloud/cyclone#1440]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
The stage gets success even when the quality gate not pass.

**What you expected to happen**:
When the quality gate not passes, the corresponding stage should fail.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by supereagle** [comment]
Have fixed
/close
