### ISSUE TITLE
not websocket protocol

### ISSUE THREAD

**Issue by KevinMyDing** [caicloud/cyclone#149]
**Environment**
- [Include version, operating system name, and other relevant details]
- OS：mac
- Docker：
Client:
 ```
Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**What happened**
- 部署后，访问localhost:8000
- 报错：not websocket protocol

**Comment by superxi911** [comment]
cyclone server 有两个端口提供服务：
- 7099：api server 端口，提供创建版本库关联、构建版本等 cyclone 主要功能操作的 restful API
- 8000：websocket 端口，用于获取构建过程中实时日志

你是如何访问 localhost:8000 的？

**Comment by KevinMyDing** [comment]
@superxi911 我按照[安装手册](https://github.com/caicloud/cyclone/blob/master/docs/setup_zh-CN.md)的Docker方式进行安装，安装完成后，通过浏览器访问的http://localhost:8000

**Comment by superxi911** [comment]
8000端口提供的不是http服务，是websocket服务，不能这么访问，你需要建一个websocket客户端连过来

**Comment by superxi911** [comment]
这里有个小程序是我当初调试这个功能的时候用go写的一个websocket client，有兴趣可以参考 [WebsocketClient](https://github.com/superxi911/WebsocketClient)

**Comment by KevinMyDing** [comment]
好想在setup的文档中，表示localhost:8000是网页访问地址哦，那么，网页管理应该通过什么端口访问呢？

**Comment by superxi911** [comment]
噢，你说的是cyclone用于OAUTH的回调前端用户界面url的ENV配置，文档里我们并没有明说现在可以通过localhost:8000访问。前端用户界面是另一个项目，目前我们还没有开源。目前只能通过API操作cyclone
