### ISSUE TITLE
Some mistakes in setup guide docs

### ISSUE THREAD

**Issue by rootsongjc** [caicloud/cyclone#151]
There are some mistakes in setup docs:
- `scripts/build-image.sh` not exist use `scripts/build-server-image.sh` instead
- The name of clair container created by `docker-compose` is `cyclone_clair_1` not `clair_clair`.(docker-compose version 1.9.0)

**Comment by superxi911** [comment]
Close via [PR#152](https://github.com/caicloud/cyclone/pull/152)
