### ISSUE TITLE
etcd start failed

### ISSUE THREAD

**Issue by tanzhixu** [caicloud/cyclone#176]
ERROR: for cyclone_etcd_1  Cannot start service etcd: driver failed programming external connectivity on endpoint cyclone_etcd_1 (24b767714249941982970cfd2e43141ff31cdcdef92b44c73545fc4c6120a8f9): Error starting userland proxy: listen tcp 0.0.0.0:2380: bind: address already in use

ERROR: for etcd  Cannot start service etcd: driver failed programming external connectivity on endpoint cyclone_etcd_1 (24b767714249941982970cfd2e43141ff31cdcdef92b44c73545fc4c6120a8f9): Error starting userland proxy: listen tcp 0.0.0.0:2380: bind: address already in use
ERROR: Encountered errors while bringing up the project

**Comment by supereagle** [comment]
Please check whether the port `2380` has been used.

**Comment by tanzhixu** [comment]
Port 2380 has been used for etcd in my k8s cluster.

**Comment by supereagle** [comment]
This is caused by port conflict, before start ETCD, make sure that the port `2380` is not used.

**Comment by supereagle** [comment]
ETCD has been removed, so close this issue.
