### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by tanzhixu** [caicloud/cyclone#189]
When i register worker node to master use curl command:
curl -X POST -H "Content-Type: application/json" -d '{
         "name": "First Node",
         "description": "Just for test",
         "ip": "127.0.0.1",
         "docker_host": "'$DOCKER_HOST'",
         "type": "system",
         "total_resource": {
             "memory": 1024,
             "cpu": 1
         }
}' 'http://10.10.35.1:30010/api/v0.1/system_worker_nodes'
I got this error:
404: Page Not Found

**Comment by zz-bmj** [comment]
sorry，the docs are out of maintenance, and this curl command is invalid anymore, cyclone doesn't need to register worker node with command now.
and we will fix it in the near future.
@tanzhixu

**Comment by supereagle** [comment]
v0.1 API has been deprecated and removed.
/close

**Comment by zhujian7** [comment]
Could you please offer us your cyclone version? or git commit revision ID?
