### ISSUE TITLE
cyclone integrates cyclone

### ISSUE THREAD

**Issue by gaocegege** [caicloud/cyclone#21]
We could use cyclone to test and deploy cyclone, just like other CI tools.

- [x] support unit test cases
- [x] support e2e test cases

**Comment by gaocegege** [comment]
Unit testing is easy, I would do it first.

**Comment by gaocegege** [comment]
I have tried to run e2e test cases in travis but failed. Travis only supports the latest version of docker.

ref https://travis-ci.org/caicloud/cyclone/jobs/176249390

**Comment by gaocegege** [comment]
Unit Test: #51

**Comment by gaocegege** [comment]
Now there are some challenges.

1. service could not find other services, because of unknown reason.
2. worker in the worker doesn't have the same network mode so it couldn't connect to etcd and so on in the defined network.

I would figure out what makes service couldn't discover each other. And as for the second challenge, should we remove network feature now? Because we now run docker in docker, no need to isolate network alias name now.

**Comment by gaocegege** [comment]
And, the unit test is done, so we could use cyclone integrates cyclone's unit test. Maybe there is some work to do, for example, add some web hooks or something else.

**Comment by superxi911** [comment]
![wechatimg1513](https://cloud.githubusercontent.com/assets/17572231/20553147/d124215e-b18c-11e6-994a-ebd5bc3f61cd.jpeg)
So, the problem is like this. The network at A and B can't connect. I agree with your solution. The old network feature is used for isolating multi tasks. We can remove it now.

**Comment by gaocegege** [comment]
We found that when we integrate cyclone's e2e test in cyclone worker, the worker in worker couldn't find the cyclone server in worker. Because the server in the network that cyclone creates and worker in host network mode.

Now we want to add two network modes to service containers, default bridge network and the network defined when integration starts.

**Comment by superxi911** [comment]
done
