### ISSUE TITLE
Migrate from Glide to dep for dependency management

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#229]
**What happened**
From [Glide](https://github.com/Masterminds/glide):
> The Go community now has the [dep](https://github.com/golang/dep) project to manage dependencies. Please consider trying to migrate from Glide to dep.

**What you expected to happen**
Use dep instead of Glide for dependency management.

**Comment by gaocegege** [comment]
#dibs

My VPN is blocked now and maybe It will take me more time.

**Comment by supereagle** [comment]
@gaocegege  Any updates?

**Comment by supereagle** [comment]
Assign this to @LiangXugang

**Comment by gaocegege** [comment]
Sorry my VPN is down so dep does not work well for me :(

**Comment by supereagle** [comment]
@gaocegege  It does not matter :)

**Comment by supereagle** [comment]
Implemented in #397
/close
