### ISSUE TITLE
The tag of built image is not the record name when it is not empty

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#253]
**What happened**
When specify the record name, the tag of built image is the format commitID-timestamp, which is not the record name.

Perform params:
```json
        {
            "name": "v120",
            "performParams": {
                "stages": [
                    "codeCheckout",
                    "package",
                    "imageBuild",
                    "integrationTest",
                    "imageRelease",
                    "unitTest"
                ]
            },
        }
```

Built image tag: fa4fd28-171121121046

**What you expected to happen**
The tag of built image should be the record name when it is provided.

**Comment by supereagle** [comment]
This bug is introduced by #186.

**Comment by zz-bmj** [comment]
Oh no...
