### ISSUE TITLE
Travis CI sometimes times out for Go 1.7

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#257]
**What happened**
https://travis-ci.org/caicloud/cyclone/pull_requests

CI for Go 1.8 can always correctly work, but for Go 1.7 sometimes fails due to timeout.

**What you expected to happen**
Find the reason for timeout and make CI more stable.

**Anything else**
Refer to [Build times out because no output was received](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received)

**Comment by LiangXugang** [comment]
The travis_CI will be timeout without any output for a period(about 10mins)during build.With a regularly long command or compile step like this, tt is recommended to use this config in `.travis.yaml` to keep it alive.
`install: travis_wait mvn install`
Considering our build takeing 30-40 mins in Go 1.7, this config is added in `.travis.yaml`: 
`install: travis_wait 40 mvn install`

**Comment by supereagle** [comment]
Reopen this issue as the error still exists: https://travis-ci.org/caicloud/cyclone/jobs/322069862

**Comment by supereagle** [comment]
In this case, the PR is for branch `release-0.3`, which does not include the fix #273 

> Reopen this issue as the error still exists: https://travis-ci.org/caicloud/cyclone/jobs/322069862
