### ISSUE TITLE
Implement the event queue by MongoDB

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#286]
The current implement of event queue is in-memory queue and ETCD for persistence. In order to remove the ETCD to simplify architecture, need to investigate replacing ETCD with MongoDB for event persistence.

**Goals:**
* The event can not be handled by more than 2 servers at the same time.
* The event can be added back if can not handled.
* The priority of added back events will be reduced, so they will wait for more time to be handled.

**Comment by LiangXugang** [comment]
This issue has been discussed in [Refactor of Job manager](https://github.com/caicloud/cyclone/issues/285)

**Comment by LiangXugang** [comment]
#285

**Comment by supereagle** [comment]
The investigation has be finished, please refer to the Demo: [mongoMQ](https://github.com/LiangXugang/demo/tree/master/mongoMQ). So close it.
