### ISSUE TITLE
Use log files in cyclone server to persist pipeline record logs

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#288]
### Real-time log

When the worker is running, it will send the logs to server in real-time, the server will temporarily store these real-time logs in Kafka. After the build finished, the server will pull all logs of this build from Kafka, and store them in MongoDB.

If the users want real-time log, the server will periodically pull the log from Kafka, and send them to users. **Even this build has finished, and all of its log has been stored in MongoDB, the server still gets its real-time log in this way.**

### Static log

If the build has finished, all of its log has been stored in MongoDB, so the server gets its log from MongoDB and send to users.

## Goals

* Server needs to support horizontal autoscaling, all instances can access all logs.
* The log file can be wrote and read at the same time.
* The new content can be read in real-time while writing logs into log files.

## Solution

Store the logs in log files in server.

* For multiple server instances, needs share storage for log files between them. If the server is deployed in K8s, PV and PVC can be used as the share storage. If the server is out of k8s, NFS such as Glusterfs and CephFS can be used as the share storage.
* When the worker is running, the server will repeatedly append these logs into log files. If users want the real-time log, the server needs to watch the change of log files after read all of its content.
* The folder structure of these log files should be carefully designed. These files should be unique and easily found.

## Discussions

* Store all logs of one build in one file, or separate them according to the stages, and one log file for each stage.

**Comment by supereagle** [comment]
Have written the demo: [websocket/examples/filewatch/](https://github.com/supereagle/websocket/tree/demo/examples/filewatch)

Currently, this demo can watch the changes of the file and read its all content, but still can not get the added content.

**Comment by ddysher** [comment]
server queries worker and save to its log files?  is it possible to distribute the load to worker?
> When the worker is running, the server will repeatedly append these logs into log files.

**Comment by supereagle** [comment]
Have implemented.
/close
