### ISSUE TITLE
add "HOWTO test the code(unit test and e2e test)"

### ISSUE THREAD

**Issue by gaocegege** [caicloud/cyclone#33]
We need a document for anyone wanting to either write code which directly accesses the Cyclone API, or to contribute directly to the Cyclone project. It should include:

- [x] API doc(Just move the  API doc to this document)
- [x] The process of developing and contributing code to the Cyclone project. (Same as https://github.com/kubernetes/kubernetes/blob/master/docs/devel/README.md)
- [x] HOWTO setup dev environment
- [ ] HOWTO test the code(unit test and e2e test)

**Comment by gaocegege** [comment]
There is one task to do here: HOWTO test the code(unit test and e2e test)

**Comment by superxi911** [comment]
After you solve this issue [#21](https://github.com/caicloud/cyclone/issues/21) ,  I will create one CI service in our public platform to do e2e test.
