### ISSUE TITLE
Connect MongoDB with username and password

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#481]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/assign
/priority p1

**Comment by C0reFast** [comment]
can use mongodb URL like "mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]" as MONGODB_HOST to use db auth, and the defaultDBName should be "" to use the db defined by URI https://github.com/caicloud/cyclone/blob/master/pkg/store/store.go#L29
