### ISSUE TITLE
Retry is needed.

### ISSUE THREAD

**Issue by bbbmj** [caicloud/cyclone#528]
Log:

```
Stage: Code checkout status: start
exit status 128Stage: Code checkout status: fail with error: exit status 128
Code checkout fails : exit status 128
```

code checkout sometime block due to network instability，retry is needed.

/kind enhancement
/cc @zhujian7 @supereagle

**Comment by zhujian7** [comment]
Retry does not work well.
![image](https://user-images.githubusercontent.com/36154065/43828289-a554918e-9b2e-11e8-8bd8-b8ad602cc4a0.png)

**Comment by zhujian7** [comment]
cyclone will retry to execute pipeline while lack of resources. but there is no retry logic of `code checkout failed`.

**Comment by supereagle** [comment]
This issue talks about retry for pipeline failure, not for lack of resources

**Comment by zhujian7** [comment]
have fixed by https://github.com/caicloud/cyclone/pull/560
