### ISSUE TITLE
./scripts/build-image.sh failed

### ISSUE THREAD

**Issue by wanghaoran1988** [caicloud/cyclone#53]
./scripts/build-image.sh 
+++++ Start building cyclone server
can't load package: package github.com/caicloud/cyclone: open /go/src/github.com/caicloud/cyclone: permission denied

**Comment by wanghaoran1988** [comment]
docker run -u 0 -t -i -v `pwd`:/go/src/github.com/caicloud/cyclone \
-e GOPATH=/go:/go/src/github.com/caicloud/cyclone/vendor golang:1.6-alpine sh
/go # cd /go/src/github.com/caicloud/cyclone/vendor
/go/src/github.com/caicloud/cyclone/vendor # ls -rlt
ls: can't open '.': Permission denied
total 0

**Comment by wanghaoran1988** [comment]
We need to disable selinux if we run on centos/redhat using sudo setenforce 0

**Comment by gaocegege** [comment]
Thanks for the issue and PR, we would test it ASAP :)
