### ISSUE TITLE
NPM speedup does not work

### ISSUE THREAD

**Issue by zhujian7** [caicloud/cyclone#537]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

npm speedup does not work, because executing `npm run build` cached dependences in `node_modules` instead of `/root/.npm`

**What you expected to happen**:

npm speedup work well. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by supereagle** [comment]
No need any more

/close
