### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by allensimonlv** [caicloud/cyclone#539]
When i register worker node to master use curl command:
curl -X POST -H "Content-Type: application/json" -d '{
       "name": "myTestCloud",
       "type": "Docker",
       "docker": {
           "host": "unix:///var/run/docker.sock"
       }
}' 'http://cyclone.kt.u51-inc.com/api/v1/clouds'
I got this error:
404 Page Not Found

**Comment by zhujian7** [comment]
Could you please offer us your cyclone version? or git commit revision ID?

**Comment by allensimonlv** [comment]
commit revision ID is: 06ac143f24ef06a284a21539a27a927d3c17f2b3

**Comment by zhujian7** [comment]
@allensimonlv Thanks for reporting the issues.
Does your cyclone run by docker container? could you please try to execute  `curl http://localhost:7099/api/v1/projects` **in your cyclone container**, and show me the results.

**Comment by huapox** [comment]
with the same problem, curl http://localhost:7099/api/v1/projects  return:
{
  "metadata": {
   "total": 0
  },
  "items": []
 }

**Comment by zhujian7** [comment]
@huapox  The result shows it is normal, i guess the return code you got is 200 instead of 404.

**Comment by supereagle** [comment]
@huapox  You need to first create a project, please refer to [Create a project](https://github.com/caicloud/cyclone/blob/master/docs/quick-start.md#create-a-project)

**Comment by huapox** [comment]
@supereagle  Okay, i'll try it latter.  

Just want to get the page like this's represents: https://github.com/caicloud/cyclone/blob/master/docs/functions.md

I've viewed multi branches of this repo, just can't find some front page's code that matches the picture of the page.

Is the web page opensourced?

**Comment by zhujian7** [comment]
I am regret to say that the front page's code is closed source. 
> Is the web page opensourced?

**Comment by supereagle** [comment]
@huapox   What about the result you have tried latter?

**Comment by chulinx** [comment]
@zhujian7 求开源web ui 😙

**Comment by zhujian7** [comment]
wow , @qiuxiaolian Is there a plan to do it? [Facepalm]

**Comment by supereagle** [comment]
Cyclone with UI has been released, you can follow [quick-start](https://github.com/caicloud/cyclone#quick-start) to have a try.
