### ISSUE TITLE
worker node docker version verification

### ISSUE THREAD

**Issue by gaocegege** [caicloud/cyclone#55]
Now we check the docker version in worker node to make sure that the version is same as [WORKER_NODE_DOCKER_VERSION](https://github.com/caicloud/cyclone/blob/4567cb7df63ef454c49c2c172796695b236ed788/api/rest/worker_node.go#L31) defined in circle server.

I think we should research the changelog of docker and reduce the claim about docker version :) Maybe `above 1.10` is OK.

**Comment by xiaomuqiao** [comment]
When we use docker 1.9.0,  we encountered the problem of communication failed  between the containers, especially kafka when use docker network feature. But docker 1.10.1 can solve that problem. Then consider the new docker version changes relatively large, so we doesn't verify whether the newer version is the normal version. So your suggestion is very good,   go to verify this thing.

**Comment by gaocegege** [comment]
Yeah, docker network is a new feature in 1.10

**Comment by superxi911** [comment]
I have modified the verification. If the node's docker version is later than v1.10.0, the node can be add into cluster.
