### ISSUE TITLE
get log api returns wrong content-type header

### ISSUE THREAD

**Issue by C0reFast** [caicloud/cyclone#589]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

```
curl -v "http://cyclone.example.com/apiv1/projects/teste/pipelines/test/records/5bd27bf9d8d25d0001f201c5/logs?stage=package"

> Host: cyclone.example.com
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 26 Oct 2018 02:35:57 GMT
< Content-Type: application/json
< Content-Length: 248
< Connection: keep-alive
< 
Stage: Package status: start
$ mkdir -p /usr/local/go/src/test
$ ln -s `pwd` /usr/local/go/src/test
$ cd /usr/local/go/src/nevis.io/test
$ echo test
Stage: Package status: finish
```
the response Content-Type should be `text/plain`, not `application/json`

**Comment by C0reFast** [comment]
https://github.com/caicloud/cyclone/pull/590 could fix this issue.

**Comment by zhujian7** [comment]
@C0reFast, thank you for reporting the issue.
And i reproduced the problem, but i am confused why [this line](https://github.com/caicloud/cyclone/blob/master/pkg/api/v1/handler/pipelineRecord.go#L189) did not work well.
I will track it. 
Thank you again.
