### ISSUE TITLE
[bug] Must create cyclone-secret when create workflow

### ISSUE THREAD

**Issue by codeflitting** [caicloud/cyclone#640]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/cc @cd1989 
/cc @supereagle 

same with # https://github.com/caicloud/cyclone/issues/639 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by youngerzz** [comment]
/assign @cd1989 
workflow 鉴权（namespace）方面，当前非 default namespace 下 workflow 的体验不好，需要 hack pv、secret 等
建议补充 namespace 的考虑并充分验证，否则后续补充鉴权相关功能时很难设计（/捂脸，clever 的苦痛经历），thx

**Comment by supereagle** [comment]
Have fixed

/close
