### ISSUE TITLE
Worker逻辑有问题？

### ISSUE THREAD

**Issue by C0reFast** [caicloud/cyclone#642]
https://github.com/caicloud/cyclone/blob/d820ece2b6d529ddee1b5caece11022752c6803c/pkg/worker/worker.go#L119

这里以及下面几个stage的判断，是不是应该只有在err != nil 时进行？

**Comment by zhujian7** [comment]
@C0reFast Yes, It is my fault, I have fixed that. Thanks for submitting the issue.

**Comment by zhujian7** [comment]
@C0reFast BTW, we are designing and developing cyclone 2.0. Are you interested in doing that with us? We all look forward to your joining.

**Comment by C0reFast** [comment]
> @C0reFast BTW, we are designing and developing cyclone 2.0. Are you interested in doing that with us? We all look forward to your joining.

@zhujian7 之前没看到这个消息，肯定很想一起开发，需要怎么加入？

**Comment by cd1989** [comment]
欢迎加入 Cyclone 微信群来进一步讨论：

![image](https://user-images.githubusercontent.com/16573984/53064750-e8e4e600-3503-11e9-94fb-3ef6e976af19.png)
