### ISSUE TITLE
tenant management module (internally refer to supereagle's user scenario 1)

### ISSUE THREAD

**Issue by artecher** [caicloud/cyclone#652]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

Implement tenant management module (internally refer to supereagle's user scenario 1)
- add tenant
- delete tenant
- update tenant
- list tenants

#100

**Comment by supereagle** [comment]
There will be default tenant if users do not add tenant. So the feature is low priority.

/priority p1

**Comment by supereagle** [comment]
Create #705 for default tenant.

**Comment by supereagle** [comment]
Not needed any more
/close
