### ISSUE TITLE
create and publish workflow module -- orchestration (internally refer to supereagle's user scenario 2)

### ISSUE THREAD

**Issue by artecher** [caicloud/cyclone#653]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

create and publish workflow module -- orchestration (internally refer to supereagle's user scenario 2)
- read and list stage templates #706
- orchestrate stages #708

#100

**Comment by supereagle** [comment]
Have done
/close
