### ISSUE TITLE
workflow module (internally refer to supereagle's user scenario 3)

### ISSUE THREAD

**Issue by artecher** [caicloud/cyclone#654]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

workflow module (internally refer to supereagle's user scenario 3)
- manually trigger a workflow and input necessary information
- list workflow

#100

**Comment by supereagle** [comment]
xref: #709

**Comment by supereagle** [comment]
Have done
/close
