### ISSUE TITLE
monitor workflow execution (internally refer to supereagle's user scenario 3)

### ISSUE THREAD

**Issue by artecher** [caicloud/cyclone#655]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

monitor workflow execution (internally refer to supereagle's user scenario 3)
- execution status
- log

#100

**Comment by supereagle** [comment]
xref: #709

**Comment by supereagle** [comment]
Have done
/close
