### ISSUE TITLE
Integration Center

### ISSUE THREAD

**Issue by cd1989** [caicloud/cyclone#671]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

### Function Details

**Integration Center** manages external services such as SCM(Git, SVN), Docker registry.
Each service has one type: `git`, `svn`, `registry`. For some service type, there can be subTypes, for example, `git` can have subType `gitlab`, `github`.

This function should support:

- CRUD of integrated service 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by supereagle** [comment]
Have done

/close
