### ISSUE TITLE
Stage Template Module

### ISSUE THREAD

**Issue by cd1989** [caicloud/cyclone#672]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

### Function Details

Stage templates serve for concrete user scenarios such as CI pipeline,  we can create
templates for source build stage, unit test stage, source code scan, build image, etc.

**Action iterms:**
- [x] Inner CI stage template #706
- [x] Support customized stage template #707

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by supereagle** [comment]
Have done

/close
