### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by cd1989** [caicloud/cyclone#673]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

### Function Details

In Cyclone, Workflow, State, Resources are management in projects. A project includes
Workflows that share some common characteristics: belong to the same team, have similar configurations, serve for the same purpose, etc.

Projects hold some common properties of all Workflows within them. For example, external service auth, resource quotas.

Under a project, there are three kinds of subjects to manage:

- Resources: Resources that would be shared within the project
- Stages: Stages that would be shared within the project
- Wofkflows: Workflows that run specific tasks.

Under a Workflow, also should mange:

- WorkflowRuns: Record of Workflow executions #709
- Triggers: Trigger of Workflow #978

Should divide this issue to sub-issues.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by supereagle** [comment]
Have finished most works exclude workflow trigger management. Will track the left work by #978.

/close
