### ISSUE TITLE
Base Stage instead of Stage Template

### ISSUE THREAD

**Issue by cd1989** [caicloud/cyclone#689]
### Proposal

Allow create new stages from base stages.

Similar to images, we can use base stage to produce new stages. With this mechanism, stage template CRD can be removed (it's not used actually by now).

In the current design, stage itself can also be used as template, and the stage template almost the same with stage. Seems duplicated definition.

**Benefits with base stage**
- Reduce the isolated state template stage, less concept
- Easy to understand, same to docker images
- Better extensibility, any stage can be used as base stage to produce new stages

@zhujian7 @supereagle @ddysher

**Comment by supereagle** [comment]
As discuss offline, stage inheritance will make it difficult to manage stages, so will not support this now.

The only difference between stages and stage templates is that stages can execute, but stage templates can not. There is no need to define another CRD for stage templates. We can add a label for stages to support stage templates.
