### ISSUE TITLE
cache docker images in worker container.

### ISSUE THREAD

**Issue by gaocegege** [caicloud/cyclone#69]
Now we pull the images every time we run the integration step. Maybe we could mount a volume to /var/lib/docker, or something else.

**Comment by superxi911** [comment]
You can discuss with @zoumo to improve saving of docker images next month.

**Comment by gaocegege** [comment]
OK, I have tried to mount /var/lib/docker to container but the docker daemon hangs, maybe we could dive further into docker's local image storage.

**Comment by gaocegege** [comment]
I have a immature idea, we could mount a dir to /var/lib/docker in worker, but it requires the user to create a  dir first before they register worker nodes into cyclone.

**Comment by superxi911** [comment]
How to isolate worker? The workers run in the same node may use the same dir.
> I have a immature idea, we could mount a dir to /var/lib/docker in worker, but it requires the user to create a dir first before they register worker nodes into cyclone.

**Comment by zoumo** [comment]
I think we should not mount /var/lib/docker directly, maybe mounting dirs such as /var/lib/docker/images or /var/lib/docker/graph will work, but it requires worker has the same version of host machine

**Comment by superxi911** [comment]
We will make a new planning.
