### ISSUE TITLE
Support default tenant

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#705]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Cyclone supports multi-tenant, but it can also be used as a single tenant. There will be a default tenant `cyclone` if users do not add tenant.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/priority p0

**Comment by zhujian7** [comment]
When cyclone-server start, will create default tenant `admin`.
