### ISSUE TITLE
WorkflowRuns management

### ISSUE THREAD

**Issue by supereagle** [caicloud/cyclone#709]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

WorkflowRuns are the execution records of Workflow. One WorkflowRun will records status for one running of Workflow, includes parameters, logs, results, stages and so on.

Cyclone supports manually triggering workflows, and viewing the running details through workflowruns.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by cd1989** [comment]
Finished for the first phrase.
