### ISSUE TITLE
make container failed

### ISSUE THREAD

**Issue by chenyu85** [caicloud/cyclone#741]
when use command "make container",the errors occured `Unable to find image 'test.caicloudprivatetest.com/release/golang:1.10-alpine3.8' locally
docker: Error response from daemon: Get https://test.caicloudprivatetest.com/v2/: dial tcp: lookup test.caicloudprivatetest.com on 114.114.114.114:53: no such host.`

**Comment by cd1989** [comment]
`test.caicloudprivatetest.com` is our own registry, when you run locally, you set set it to docker hub.

```
make container REGISTRIES=docker.io/library
```

I will set default value to `docker.io/library`

**Comment by chenyu85** [comment]
Use docker hub in Makefile,there's another question `github.com/caicloud/cyclone/pkg/workflow/coordinator
/bin/sh: 3: Bad substitution
Makefile:134: recipe for target 'container' failed
make: *** [container] Error 2`

**Comment by cd1989** [comment]
Please use `bash` instead of `sh` to run it.

**Comment by chenyu85** [comment]
16.04.1-Ubuntu

**Comment by chenyu85** [comment]
> Please try to use `bash` instead of `sh` to run it.
> 
> And it would be helpful if you can attach your environment information, like OS, Shell.

16.04.1-Ubuntu

**Comment by chenyu85** [comment]
> Please try to use `bash` instead of `sh` to run it.
this error was occured when I run the ‘make container’,Do you mean I should change the Makefile?

**Comment by cd1989** [comment]
I will fix it. You can add `SHELL := /bin/bash` to the top of the Makefile to specify `bash` instead of `sh`.
