### ISSUE TITLE
worker cluster did not closed when delete cluster type integration

### ISSUE THREAD

**Issue by zhujian7** [caicloud/cyclone#791]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
worker cluster did not closed when delete cluster type integration

**What you expected to happen**:
cluster type integration is a little special, if `isWorkerCluster` is true, this integration should not be deleted directly, we need to close the worker cluster firstly.

How to close worker cluster?
- if the integration cluster `isControlCluster` is true, we need to delele quota and pvc
- if the integration cluster `isControlCluster` is false, we need to delele quota, pvc and namespace

in addition, if namespace or pvc is configured by user, instead of creating by cyclone, we will not delete it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/priority p0

**Comment by supereagle** [comment]
Has this been fixed?

**Comment by zhujian7** [comment]
have been fixed
/close
