### ISSUE TITLE
resolver supports SVN

### ISSUE THREAD

**Issue by zhujian7** [caicloud/cyclone#794]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

> /kind feature

**What happened**:
resolver only supports git, image and kv by now
**What you expected to happen**:
resolver needs to support svn
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/priority p0

**Comment by supereagle** [comment]
Have done

/close
