### ISSUE TITLE
Install cyclone components into cyclone-system namespace

### ISSUE THREAD

**Issue by zhujian7** [caicloud/cyclone#885]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

> /kind feature

**What happened**:
Cyclone system components are installed in `default` namespace at now, we hope to install them into `cyclone-system` namespace in the future.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/priority p1

**Comment by supereagle** [comment]
Have supported to install in a specified namespace. Refer to [Installation Guide](https://github.com/caicloud/cyclone/blob/master/docs/installation.md).

/close
