### ISSUE TITLE
add badge support

### ISSUE THREAD

**Issue by gaocegege** [caicloud/cyclone#91]
We should support badge in cyclone, just like travis.

**Comment by gaocegege** [comment]
close via #90, things we need to do now is re-deploy cyclone and add badges to readme.

**Comment by superxi911** [comment]
close via [#92](https://github.com/caicloud/cyclone/pull/92)

**Comment by gaocegege** [comment]
We don't update the badge of e2e test and unit test now, because it needs to re-compile and restart cyclone. So if you do it in the future, tell me and I could add badges to readme.

**Comment by superxi911** [comment]
ok
